<?php
include_once "Square.php";

class Cube extends Square
{
    public function __construct($name, $width)
    {
        parent::__construct($name, $width);
    }

    public function calculateArea()
    {
        return parent::calculateArea()*6; // TODO: Change the autogenerated stub
    }

    public function calculateVolume(){
        return parent::calculateArea()*$this->width;
    }
}