<?php
include_once "Point2D.php";

class Point3D extends Point
{
    private $z;

    public function __construct($x, $y, $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    /**
     * @return mixed
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * @param mixed $z
     */
    public function setZ($z)
    {
        $this->z = $z;
    }

    public function setXYZ($x, $y, $z)
    {
        parent::setXY($x, $y);
        $this->$z = $z;
    }

    public function getXYZ()
    {
        parent::getXY();
        array_push($arr, $this->z);
        return $arr;
    }

   public function __toString()
   {
       return "<br>".parent::__toString().", z: ".$this->z; // TODO: Change the autogenerated stub
   }
}