<?php
include_once "Circle.php";

class Cylinder extends Circle
{
    protected $height;

    public function __construct($name, $color, $radius, $height)
    {
        parent::__construct($name, $color, $radius);
        $this->height = $height;
    }

    /**
     * @return mixed
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * @param mixed $height
     */
    public function setHeight($height)
    {
        $this->height = $height;
    }
    //volume:
    public function calculateVolume(){
        return $this->calculateArea()*$this->height;
    }
    public function toString()
    {
        return "Cylinder info: ".parent::toString()."Height: ".$this->height."<br>Volume: ".$this->calculateVolume(); // TODO: Change the autogenerated stub
    }
}