<?php

include_once "Point.php";
class movablePoint extends Point
{
    private $xSpeed = 0.0;
    private $ySpeed = 0.0;


    public function __construct($x, $y, $xSpeed, $ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    /**
     * @return float
     */
    public function getXSpeed()
    {
        return $this->xSpeed;
    }

    /**
     * @return float
     */
    public function getYSpeed()
    {
        return $this->ySpeed;
    }

    /**
     * @param float $xSpeed
     */
    public function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @param float $ySpeed
     */
    public function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }

    public function setSpeed($xSpeed, $ySpeed)
    {
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    public function __toString()
    {
        return "<br>".parent::__toString() . ", speed = ($this->ySpeed, $this->ySpeed)"; // TODO: Change the autogenerated stub
    }

    public function move()
    {
        $x = self::getX();
        $y = self::getY();
        self::setX($x+= $this->xSpeed);
        self::setY($y+= $this->ySpeed);
        return $this;
    }
}